"""create sat organization attrs

Revision ID: 0a888d96ec26
Revises: a329e083915f
Create Date: 2026-05-15 23:49:36.934941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0a888d96ec26'
down_revision: Union[str, Sequence[str], None] = 'a329e083915f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sat_organization_attrs",

        sa.Column("hub_org_hash_key",sa.String(length=64),nullable=False,),
        sa.Column("hashdiff", sa.String(length=64), nullable=False, ),
        sa.Column("load_date", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False,),
        sa.Column("full_name", sa.Text(), nullable=True, ),
        sa.Column("short_name", sa.Text(), nullable=True,),
        sa.Column("ogrn", sa.Text(),  nullable=True,),
        sa.Column("inn", sa.Text(), nullable=True,),
        sa.Column("address", sa.Text(), nullable=True,),
        sa.Column("ved_affiliation_id", sa.Text(), nullable=True,),
        sa.Column("inclusion_date", sa.Date(), nullable=True,),
        sa.Column("record_source", sa.Text(), nullable=False,),
        sa.ForeignKeyConstraint(
            ["hub_org_hash_key"],
            ["nsi.hub_organization.hub_org_hash_key"],
        ),
        sa.PrimaryKeyConstraint(
            "hub_org_hash_key",
            "hashdiff",
        ),
        schema="nsi",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sat_organization_attrs', schema='nsi')
    # ### end Alembic commands ###
