"""change valid_from valid_to to datetime

Revision ID: e9d31cc12c2e
Revises: 9cc5c0711395
Create Date: 2026-05-16 23:02:40.459308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e9d31cc12c2e'
down_revision: Union[str, Sequence[str], None] = '9cc5c0711395'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sat_organization_changes",
        "valid_from",
        existing_type=sa.Date(),
        type_=sa.DateTime(timezone=True),
        schema="nsi",
    )
    op.alter_column(
        "sat_organization_changes",
        "valid_to",
        existing_type=sa.Date(),
        type_=sa.DateTime(timezone=True),
        schema="nsi",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sat_organization_changes",
        "valid_from",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.Date(),
        schema="nsi",
    )

    op.alter_column(
        "sat_organization_changes",
        "valid_to",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.Date(),
        schema="nsi",
    )
    # ### end Alembic commands ###
