"""create sat organization changes

Revision ID: 9cc5c0711395
Revises: 0a888d96ec26
Create Date: 2026-05-16 00:15:20.218029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9cc5c0711395'
down_revision: Union[str, Sequence[str], None] = '0a888d96ec26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sat_organization_changes",
        sa.Column(
            "change_id",sa.BigInteger(), autoincrement=True,nullable=False,),
        sa.Column("loaded_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),  nullable=False,),
        sa.Column("hub_org_hash_key", sa.String(length=64), nullable=False,),
        sa.Column("attribute_name", sa.String(length=255), nullable=False,),
        sa.Column("attribute_value", sa.Text(), nullable=True,),
        sa.Column("valid_from",  sa.Date(),nullable=False,),
        sa.Column("valid_to", sa.Date(), nullable=True,),

        sa.ForeignKeyConstraint(
            ["hub_org_hash_key"],
            ["nsi.hub_organization.hub_org_hash_key"],
        ),

        sa.PrimaryKeyConstraint(
            "change_id",
        ),
        schema="nsi",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sat_organization_changes', schema='nsi')
    # ### end Alembic commands ###
