"""create raw medical organizations

Revision ID: d0f3b031a452
Revises: 
Create Date: 2026-05-15 17:41:11.530836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd0f3b031a452'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_medical_organizations',
    sa.Column('raw_hash_key', sa.String(length=64), nullable=False),
    sa.Column('source_version', sa.Text(), nullable=False),
    sa.Column('loaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('unique_id', sa.Text(), nullable=True),
    sa.Column('oid', sa.Text(), nullable=True),
    sa.Column('oid_non_unique', sa.Text(), nullable=True),
    sa.Column('full_name', sa.Text(), nullable=True),
    sa.Column('short_name', sa.Text(), nullable=True),
    sa.Column('unique_parent_id', sa.Text(), nullable=True),
    sa.Column('healthcare_system_entity_code', sa.Text(), nullable=True),
    sa.Column('healthcare_system_entity_name', sa.Text(), nullable=True),
    sa.Column('inn', sa.Text(), nullable=True),
    sa.Column('kpp', sa.Text(), nullable=True),
    sa.Column('ogrn', sa.Text(), nullable=True),
    sa.Column('region_rf_code', sa.Text(), nullable=True),
    sa.Column('region_rf_name', sa.Text(), nullable=True),
    sa.Column('ownership_form', sa.Text(), nullable=True),
    sa.Column('departmental_affiliation_identifier', sa.Text(), nullable=True),
    sa.Column('departmental_affiliation', sa.Text(), nullable=True),
    sa.Column('founder', sa.Text(), nullable=True),
    sa.Column('date_of_record_deletion', sa.Date(), nullable=True),
    sa.Column('reason_of_record_deletion', sa.Text(), nullable=True),
    sa.Column('date_of_record_creation', sa.Date(), nullable=True),
    sa.Column('last_modification_date', sa.Date(), nullable=True),
    sa.Column('organization_level', sa.Text(), nullable=True),
    sa.Column('activity_type_identifier', sa.Text(), nullable=True),
    sa.Column('activity_type', sa.Text(), nullable=True),
    sa.Column('activity_profile_id', sa.Text(), nullable=True),
    sa.Column('activity_profile', sa.Text(), nullable=True),
    sa.Column('zip_code', sa.Text(), nullable=True),
    sa.Column('cadastral_number', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('fias_version', sa.Text(), nullable=True),
    sa.Column('locality_identifier', sa.Text(), nullable=True),
    sa.Column('street_identifier', sa.Text(), nullable=True),
    sa.Column('house_identifier', sa.Text(), nullable=True),
    sa.Column('region_code', sa.Text(), nullable=True),
    sa.Column('region_name', sa.Text(), nullable=True),
    sa.Column('okato_region_code', sa.Text(), nullable=True),
    sa.Column('federal_significance_city', sa.Text(), nullable=True),
    sa.Column('settlement_name', sa.Text(), nullable=True),
    sa.Column('settlement_prefix', sa.Text(), nullable=True),
    sa.Column('street_name', sa.Text(), nullable=True),
    sa.Column('street_prefix', sa.Text(), nullable=True),
    sa.Column('house_number', sa.Text(), nullable=True),
    sa.Column('building_number', sa.Text(), nullable=True),
    sa.Column('corpus_number', sa.Text(), nullable=True),
    sa.Column('oid_head_organization_for_sp_1', sa.Text(), nullable=True),
    sa.Column('oid_sp_1', sa.Text(), nullable=True),
    sa.Column('oid_subsidiaries_sp_1', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('raw_hash_key'),
    schema='nsi'
    )
    op.create_index('ix_raw_medical_organizations_oid', 'raw_medical_organizations', ['oid'], unique=False, schema='nsi')
    op.create_index('ix_raw_medical_organizations_source_version', 'raw_medical_organizations', ['source_version'], unique=False, schema='nsi')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_raw_medical_organizations_source_version', table_name='raw_medical_organizations', schema='nsi')
    op.drop_index('ix_raw_medical_organizations_oid', table_name='raw_medical_organizations', schema='nsi')
    op.drop_table('raw_medical_organizations', schema='nsi')
    # ### end Alembic commands ###
